= STACKL Architecture:: Volume 2: Instruction Set Reference
Jonathan Thomason <jonathan.a.thomason@gmail.com>
:title-separator: ::
:doctype: book
:pdf-page-layout: cover
:outline-title: STACKL Architecture Volume 2: Instruction Set Reference
:toc:

== Preface
=== About This Book
This book is part of a multivolume work entitled the *STACKL Architecture*.

STACKL defines a virtual stack-based machine environment designed for
educational and research use in operating system and systems programming.

This table lists each volume in the series.

[width=75%,align=center]
|===
^|Title

|STACKL Architecture Volume 1: Basic Architecture

|STACKL Architecture Volume 2: Instruction Set Reference

|STACKL Architecture Volume 3: System Programming Guide
|===

[%always]
<<<

== 3 General-Purpose Instruction Reference
This chapter describes general purpose instructions for stackl.

[%always]
<<<
=== ADD

This opcode performs an addition. This instruction has the following effect:
```
Memory[SP-2] = Memory[SP-2] + Memory[SP-1]
SP--
IP++
```

[frame=none,grid=none]
|===
|Mnemonic |Opcode |Description

|ADD    |01     |
|===

==== Related Instructions
SUB

==== FLAGS Affected
None

==== Exceptions
None

[%always]
<<<
=== ADJSP

This opcode is used to adjust the stack pointer. This opcode has the following effect:
```
SP += <amount>
IP += 2
```
The `<amount>` can be a positive or negative number. The `<amount>` is in bytes, not words. If `<amount>` is not a multiple of the word size, the machine behavior will be undefined following this instruction.

[frame=none,grid=none]
|===
|Mnemonic |Opcode |Description

|ADJSP    |2E _id_ | Add _imm32_ to SP.
|===

==== Related Instructions
None

==== FLAGS Affected
None

==== Exceptions
[cols="20%,6%,9%,12%,53%"]
|===
^|Exception ^|Real ^|Virtual ^|Protected ^|Cause of Exception

| Alignment check, #AC ^| ^|X ^|X | An unaligned memory reference was performed
|===
