= STACKL Architecture:: Volume 2: Instruction Set Reference
Jonathan Thomason <jonathan.a.thomason@gmail.com>
:title-separator: ::
:doctype: book
:pdf-page-layout: cover
:outline-title: STACKL Architecture Volume 2: Instruction Set Reference
:toc:

== Preface
=== About This Book
This book is part of a multivolume work entitled the *STACKL Architecture*.

STACKL defines a virtual stack-based machine environment designed for
educational and research use in operating system and systems programming.

This table lists each volume in the series.

[width=75%,align=center]
|===
^|Title

|STACKL Architecture Volume 1: Basic Architecture

|STACKL Architecture Volume 2: Instruction Set Reference

|STACKL Architecture Volume 3: System Programming Guide
|===

[%always]
<<<

== 3 General-Purpose Instruction Reference
This chapter describes general purpose instructions for stackl.

[%always]
<<<
=== ADD

==== Format
[frame=none,grid=none]
|===
|Mnemonic |Opcode |Description

|ADD    |01     |
|===

==== Purpose
This opcode performs an addition.

==== Description
None

==== Operation
```
Memory[SP-2] := Memory[SP-2] + Memory[SP-1]
SP--
IP++
```

==== Related Instructions
SUB

==== FLAGS Affected
None

==== Exceptions
None

[%always]
<<<
=== ADJSP

==== Format
[frame=all,grid=all]
|===
|Mnemonic |Opcode |Description

|ADJSP _imm32_   |2E _id_ | Add _imm32_ to SP.
|===

==== Purpose
This opcode is used to adjust the stack pointer.

==== Description
The 32-bit signed immediate can be a positive or negative number. The immediate is in bytes, not words.

==== Restrictions
If the immediate is not a multiple of the word size, the machine behavior will be undefined following this instruction.

==== Operation
```
SP += immediate
IP += 2
```

==== Related Instructions
None

==== FLAGS Affected
None

==== Exceptions
[cols="20%,6%,9%,12%,53%"]
|===
^|Exception ^|Real ^|Virtual ^|Protected ^|Cause of Exception

| Alignment check ^| ^|X ^|X | An unaligned memory reference was performed
|===
